"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import activateazuresubscriptionresponse as components_activateazuresubscriptionresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class ActivateAzureSubscriptionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    activate_azure_subscription_response: Optional[components_activateazuresubscriptionresponse.ActivateAzureSubscriptionResponse] = dataclasses.field(default=None)
    r"""ActivateAzureSubscription 200 response"""
    

