"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import batchlogreferencerequest as components_batchlogreferencerequest
from ...models.components import batchlogsessionreferenceresponse as components_batchlogsessionreferenceresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class BatchCreateReferenceProfileUploadRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    batch_log_reference_request: components_batchlogreferencerequest.BatchLogReferenceRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class BatchCreateReferenceProfileUploadResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    batch_log_session_reference_response: Optional[components_batchlogsessionreferenceresponse.BatchLogSessionReferenceResponse] = dataclasses.field(default=None)
    r"""BatchCreateReferenceProfileUpload 200 response"""
    

