"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import createsessionresponse as components_createsessionresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class CreateSessionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    create_session_response: Optional[components_createsessionresponse.CreateSessionResponse] = dataclasses.field(default=None)
    r"""A new session id that can be used to upload dataset profiles."""
    

