"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import logreferencerequest as components_logreferencerequest
from ...models.components import logsessionreferenceresponse as components_logsessionreferenceresponse
from typing import Optional


@dataclasses.dataclass
class CreateReferenceProfileUploadRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    log_reference_request: components_logreferencerequest.LogReferenceRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreateReferenceProfileUploadResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    log_session_reference_response: Optional[components_logsessionreferenceresponse.LogSessionReferenceResponse] = dataclasses.field(default=None)
    r"""CreateReferenceProfileUpload 200 response"""
    

