"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import accountuser as components_accountuser
from ...models.components import createaccountuserrequest as components_createaccountuserrequest
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class CreateAccountUserRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    create_account_user_request: components_createaccountuserrequest.CreateAccountUserRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreateAccountUserResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    account_user: Optional[components_accountuser.AccountUser] = dataclasses.field(default=None)
    r"""CreateAccountUser 200 response"""
    

