"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import createreferenceprofilerequest as components_createreferenceprofilerequest
from ...models.components import createreferenceprofileresponse as components_createreferenceprofileresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class CreateReferenceProfileRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    r"""The unique model ID in your company."""
    create_reference_profile_request: components_createreferenceprofilerequest.CreateReferenceProfileRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreateReferenceProfileResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    create_reference_profile_response: Optional[components_createreferenceprofileresponse.CreateReferenceProfileResponse] = dataclasses.field(default=None)
    r"""The metadata for the summarized reference profile data"""
    

