"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import createdatasetprofileuploadresponse as components_createdatasetprofileuploadresponse
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import logasyncrequest as components_logasyncrequest
from typing import Optional


@dataclasses.dataclass
class CreateDatasetProfileUploadRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    log_async_request: components_logasyncrequest.LogAsyncRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreateDatasetProfileUploadResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    create_dataset_profile_upload_response: Optional[components_createdatasetprofileuploadresponse.CreateDatasetProfileUploadResponse] = dataclasses.field(default=None)
    r"""CreateDatasetProfileUpload 200 response"""
    

