"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import adminreportresponse as components_adminreportresponse
from ...models.components import adminreporttype as components_adminreporttype
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GenerateReportRequest:
    report_type: components_adminreporttype.AdminReportType = dataclasses.field(metadata={'query_param': { 'field_name': 'report_type', 'style': 'form', 'explode': True }})
    r"""A type of admin report."""
    



@dataclasses.dataclass
class GenerateReportResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    admin_report_response: Optional[components_adminreportresponse.AdminReportResponse] = dataclasses.field(default=None)
    r"""GenerateReport 200 response"""
    

