"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import getmarketplacemetadataresponse as components_getmarketplacemetadataresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetAWSMarketplaceMetadataRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetAWSMarketplaceMetadataResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    get_marketplace_metadata_response: Optional[components_getmarketplacemetadataresponse.GetMarketplaceMetadataResponse] = dataclasses.field(default=None)
    r"""GetAWSMarketplaceMetadata 200 response"""
    

