"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import entityweightrecord as components_entityweightrecord
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetColumnWeightsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetColumnWeightsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    entity_weight_record: Optional[components_entityweightrecord.EntityWeightRecord] = dataclasses.field(default=None)
    r"""GetColumnWeights 200 response"""
    

