"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import getdefaultmembershipresponse as components_getdefaultmembershipresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetDefaultMembershipForEmailRequest:
    email: str = dataclasses.field(metadata={'query_param': { 'field_name': 'email', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetDefaultMembershipForEmailResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    get_default_membership_response: Optional[components_getdefaultmembershipresponse.GetDefaultMembershipResponse] = dataclasses.field(default=None)
    r"""GetDefaultMembershipForEmail 200 response"""
    

