"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import getdatasetmetadataresponse as components_getdatasetmetadataresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetDatasetMetadataRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetDatasetMetadataResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    get_dataset_metadata_response: Optional[components_getdatasetmetadataresponse.GetDatasetMetadataResponse] = dataclasses.field(default=None)
    r"""GetDatasetMetadata 200 response"""
    

