"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import emailnotificationaction as components_emailnotificationaction
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetEmailNotificationActionPayloadResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    email_notification_action: Optional[components_emailnotificationaction.EmailNotificationAction] = dataclasses.field(default=None)
    r"""getEmailNotificationActionPayload 200 response"""
    

