"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import modelmetadataresponse as components_modelmetadataresponse
from typing import Optional


@dataclasses.dataclass
class GetModelRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""The name of an organization"""
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The ID of a model"""
    



@dataclasses.dataclass
class GetModelResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    model_metadata_response: Optional[components_modelmetadataresponse.ModelMetadataResponse] = dataclasses.field(default=None)
    r"""A \[ModelMetadataResponse\] object if operation succeeds"""
    

