"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import profiletracesresponse as components_profiletracesresponse
from typing import Optional


@dataclasses.dataclass
class GetProfileTracesRequest:
    UNSET='__SPEAKEASY_UNSET__'
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    trace_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'trace_id', 'style': 'simple', 'explode': False }})
    limit: Optional[int] = dataclasses.field(default=UNSET, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    offset: Optional[int] = dataclasses.field(default=UNSET, metadata={'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetProfileTracesResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    profile_traces_response: Optional[components_profiletracesresponse.ProfileTracesResponse] = dataclasses.field(default=None)
    r"""GetProfileTraces 200 response"""
    

