"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import getprofileobservatorylinkrequest as components_getprofileobservatorylinkrequest
from ...models.components import getprofileobservatorylinkresponse as components_getprofileobservatorylinkresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetSessionProfileObservatoryLinkRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    get_profile_observatory_link_request: components_getprofileobservatorylinkrequest.GetProfileObservatoryLinkRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class GetSessionProfileObservatoryLinkResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    get_profile_observatory_link_response: Optional[components_getprofileobservatorylinkresponse.GetProfileObservatoryLinkResponse] = dataclasses.field(default=None)
    r"""GetSessionProfileObservatoryLink 200 response"""
    

