"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import getsessionresponse as components_getsessionresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetSessionRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetSessionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    get_session_response: Optional[components_getsessionresponse.GetSessionResponse] = dataclasses.field(default=None)
    r"""GetSession 200 response"""
    

