"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import azuremarketplacesubscriptiondetails as components_azuremarketplacesubscriptiondetails
from ...models.components import httpmetadata as components_httpmetadata
from typing import List, Optional


@dataclasses.dataclass
class ListAzureMarketplaceSubscriptionsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    azure_marketplace_subscription_details: Optional[List[components_azuremarketplacesubscriptiondetails.AzureMarketplaceSubscriptionDetails]] = dataclasses.field(default=None)
    r"""ListAzureMarketplaceSubscriptions 200 response"""
    

