"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import listuserapikeys as components_listuserapikeys
from typing import Optional


@dataclasses.dataclass
class ListAPIKeysRequest:
    UNSET='__SPEAKEASY_UNSET__'
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    user_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'query_param': { 'field_name': 'user_id', 'style': 'form', 'explode': True }})
    r"""The unique user ID in an organization."""
    



@dataclasses.dataclass
class ListAPIKeysResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    list_user_api_keys: Optional[components_listuserapikeys.ListUserAPIKeys] = dataclasses.field(default=None)
    r"""A list of objects with key ID and other metadata about the keys, but no secret values"""
    

