"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import accountuser as components_accountuser
from ...models.components import httpmetadata as components_httpmetadata
from typing import List, Optional


@dataclasses.dataclass
class ListAccountUsersRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class ListAccountUsersResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    account_users: Optional[List[components_accountuser.AccountUser]] = dataclasses.field(default=None)
    r"""ListAccountUsers 200 response"""
    

