"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import notificationaction as components_notificationaction
from typing import List, Optional


@dataclasses.dataclass
class ListNotificationActionsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class ListNotificationActionsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    notification_actions: Optional[List[components_notificationaction.NotificationAction]] = dataclasses.field(default=None)
    r"""ListNotificationActions 200 response"""
    

