"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import segmentlistresponse as components_segmentlistresponse
from typing import Optional


@dataclasses.dataclass
class ListSegmentsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The unique model ID in your company."""
    



@dataclasses.dataclass
class ListSegmentsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    segment_list_response: Optional[components_segmentlistresponse.SegmentListResponse] = dataclasses.field(default=None)
    r"""The list of segments for the dataset profile"""
    

