"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import cachekeytype as components_cachekeytype
from ...models.components import httpmetadata as components_httpmetadata
from typing import List, Optional


@dataclasses.dataclass
class ListCacheKeysRequest:
    UNSET='__SPEAKEASY_UNSET__'
    cache_key_type: components_cachekeytype.CacheKeyType = dataclasses.field(metadata={'query_param': { 'field_name': 'cache_key_type', 'style': 'form', 'explode': True }})
    pattern: Optional[str] = dataclasses.field(default=UNSET, metadata={'query_param': { 'field_name': 'pattern', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class ListCacheKeysResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    strings: Optional[List[str]] = dataclasses.field(default=None)
    r"""ListCacheKeys 200 response"""
    

