"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import debugevent as components_debugevent
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class LogDebugEventRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    r"""The resource ID to log the event to"""
    debug_event: components_debugevent.DebugEvent = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class LogDebugEventResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    string: Optional[str] = dataclasses.field(default=None)
    r"""202 if the response is accepted"""
    

