"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import asynclogresponse as components_asynclogresponse
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import transactionlogrequest as components_transactionlogrequest
from typing import Optional


@dataclasses.dataclass
class LogTransactionRequest:
    transaction_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'transaction_id', 'style': 'form', 'explode': True }})
    transaction_log_request: components_transactionlogrequest.TransactionLogRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class LogTransactionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    async_log_response: Optional[components_asynclogresponse.AsyncLogResponse] = dataclasses.field(default=None)
    r"""LogTransaction 200 response"""
    

