"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import provisionnewawsmarketplaceuserresponse as components_provisionnewawsmarketplaceuserresponse
from typing import Optional


@dataclasses.dataclass
class ProvisionAWSMarketplaceNewUserResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    provision_new_aws_marketplace_user_response: Optional[components_provisionnewawsmarketplaceuserresponse.ProvisionNewAWSMarketplaceUserResponse] = dataclasses.field(default=None)
    r"""ProvisionAWSMarketplaceNewUser 200 response"""
    

