"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import logtransactionmetadata as components_logtransactionmetadata
from typing import Optional


@dataclasses.dataclass
class StartTransactionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    log_transaction_metadata: Optional[components_logtransactionmetadata.LogTransactionMetadata] = dataclasses.field(default=None)
    r"""StartTransaction 200 response"""
    

