"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import membershipmetadata as components_membershipmetadata
from typing import Optional


@dataclasses.dataclass
class UpdateMembershipByEmailResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    membership_metadata: Optional[components_membershipmetadata.MembershipMetadata] = dataclasses.field(default=None)
    r"""UpdateMembershipByEmail 200 response"""
    

