"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import modelmetadataresponse as components_modelmetadataresponse
from ...models.components import timeperiod as components_timeperiod
from enum import Enum
from typing import Optional

class QueryParamModelType(str, Enum):
    r"""The type of model associated with the dataset"""
    CLASSIFICATION = 'CLASSIFICATION'
    REGRESSION = 'REGRESSION'
    EMBEDDINGS = 'EMBEDDINGS'
    LLM = 'LLM'
    RANKING = 'RANKING'
    MODEL_OTHER = 'MODEL_OTHER'
    DATA_SOURCE = 'DATA_SOURCE'
    DATA_STREAM = 'DATA_STREAM'
    DATA_TRANSFORM = 'DATA_TRANSFORM'
    DATA_OTHER = 'DATA_OTHER'


@dataclasses.dataclass
class UpdateModelRequest:
    UNSET='__SPEAKEASY_UNSET__'
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""The organization ID"""
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The model ID"""
    model_name: str = dataclasses.field(metadata={'query_param': { 'field_name': 'model_name', 'style': 'form', 'explode': True }})
    r"""The name of a model"""
    time_period: components_timeperiod.TimePeriod = dataclasses.field(metadata={'query_param': { 'field_name': 'time_period', 'style': 'form', 'explode': True }})
    r"""The \[TimePeriod\] for data aggregation/alerting for a model"""
    model_type: Optional[QueryParamModelType] = dataclasses.field(default=UNSET, metadata={'query_param': { 'field_name': 'model_type', 'style': 'form', 'explode': True }})
    r"""The \[ModelType\] of the dataset"""
    



@dataclasses.dataclass
class UpdateModelResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    model_metadata_response: Optional[components_modelmetadataresponse.ModelMetadataResponse] = dataclasses.field(default=None)
    r"""The \[ModelMetadataResponse\] if operation succeeds"""
    

