"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AdminReportType(str, Enum):
    r"""A type of admin report."""
    SESSIONS = 'SESSIONS'
