"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AnalyzerDiagnosticRecord:
    analyzer_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('analyzerId') }})
    metric: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metric') }})
    column_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('columnCount') }})
    segment_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('segmentCount') }})
    anomaly_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('anomalyCount') }})
    max_anomaly_per_column: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('maxAnomalyPerColumn') }})
    min_anomaly_per_column: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('minAnomalyPerColumn') }})
    avg_anomaly_per_column: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('avgAnomalyPerColumn') }})
    

