"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .analyzersegmentdiagnosticrecord import AnalyzerSegmentDiagnosticRecord
from .analyzersegmentfailurerecord import AnalyzerSegmentFailureRecord
from dataclasses_json import Undefined, dataclass_json
from typing import List
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AnalyzerSegmentsDiagnosticResponse:
    noisy_segments: List[AnalyzerSegmentDiagnosticRecord] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('noisySegments') }})
    failed_segments: List[AnalyzerSegmentFailureRecord] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('failedSegments') }})
    

