"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AnalyzerSegmentColumnDiagnosticRecord:
    column: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('column') }})
    total_anomalies: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('totalAnomalies') }})
    batch_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('batchCount') }})
    

