"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .segment import Segment
from dataclasses_json import Undefined, dataclass_json
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AnalyzerSegmentFailureRecord:
    segment: Segment = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('segment') }})
    total_failed: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('totalFailed') }})
    

