"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AzureMarketplaceContactPayload:
    email_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('emailId') }})
    object_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('objectId') }})
    tenant_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tenantId') }})
    puid: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('puid') }})
    

