"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .azuremarketplacecontactpayload import AzureMarketplaceContactPayload
from dataclasses_json import Undefined, dataclass_json
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AzureMarketplaceSubscriptionDetails:
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    publisher_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('publisherId') }})
    offer_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offerId') }})
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    saas_subscription_status: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('saasSubscriptionStatus') }})
    beneficiary: AzureMarketplaceContactPayload = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('beneficiary') }})
    purchaser: AzureMarketplaceContactPayload = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('purchaser') }})
    plan_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('planId') }})
    

