"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .logsessionreferenceresponse import LogSessionReferenceResponse
from dataclasses_json import Undefined, dataclass_json
from typing import List
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class BatchLogSessionReferenceResponse:
    r"""Response payload for uploading reference profiles."""
    references: List[LogSessionReferenceResponse] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('references') }})
    observatory_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('observatoryUrl') }})
    

