"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CacheKeyType(str, Enum):
    RATE_LIMIT_BUCKET = 'RateLimitBucket'
    API_KEY_LAST_USED = 'ApiKeyLastUsed'
