"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PartialSuccess:
    UNSET='__SPEAKEASY_UNSET__'
    rejected_spans: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('rejectedSpans') }})
    error_message: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorMessage'), 'exclude': lambda f: f is PartialSuccess.UNSET }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ExportTraceServiceResponse:
    UNSET='__SPEAKEASY_UNSET__'
    partial_success: Optional[PartialSuccess] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('partialSuccess'), 'exclude': lambda f: f is ExportTraceServiceResponse.UNSET }})
    

