"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MarketplaceDimensions(str, Enum):
    FREE = 'FREE'
    MODELS_2 = 'MODELS_2'
    MODELS_3 = 'MODELS_3'
    MODELS_4 = 'MODELS_4'
    MODELS_5 = 'MODELS_5'
    BY_QUANTITY = 'BY_QUANTITY'
    ENTERPRISE = 'ENTERPRISE'
