"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .ubernotificationschedule import UberNotificationSchedule
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional
from whylabs_client import utils

class OrganizationMetadataSubscriptionTier(str, Enum):
    FREE = 'FREE'
    PAID = 'PAID'
    AWS_MARKETPLACE = 'AWS_MARKETPLACE'
    SUBSCRIPTION = 'SUBSCRIPTION'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrganizationMetadataNotificationSettings:
    r"""Settings that control how and when notifications are delivered."""
    email_settings: UberNotificationSchedule = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('emailSettings') }})
    r"""Combination of all possible schedule types, a hacky workaround for bugs in generated clients that use polymorphic types.
    There are three types of schedules. Weekly, Daily, and Individual. You need to set the right fields for each one.

    Weekly:
        enabled, cadence=WEEKLY, dayOfWeek, local24HourOfDay, localMinuteOfHour, localTimezone

    Daily:
        enabled, cadence=DAILY, local24HourOfDay, localMinuteOfHour, localTimezone

    Individual:
        enabled, cadence=INDIVIDUAL
    """
    slack_settings: UberNotificationSchedule = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('slackSettings') }})
    r"""Combination of all possible schedule types, a hacky workaround for bugs in generated clients that use polymorphic types.
    There are three types of schedules. Weekly, Daily, and Individual. You need to set the right fields for each one.

    Weekly:
        enabled, cadence=WEEKLY, dayOfWeek, local24HourOfDay, localMinuteOfHour, localTimezone

    Daily:
        enabled, cadence=DAILY, local24HourOfDay, localMinuteOfHour, localTimezone

    Individual:
        enabled, cadence=INDIVIDUAL
    """
    pager_duty_settings: UberNotificationSchedule = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pagerDutySettings') }})
    r"""Combination of all possible schedule types, a hacky workaround for bugs in generated clients that use polymorphic types.
    There are three types of schedules. Weekly, Daily, and Individual. You need to set the right fields for each one.

    Weekly:
        enabled, cadence=WEEKLY, dayOfWeek, local24HourOfDay, localMinuteOfHour, localTimezone

    Daily:
        enabled, cadence=DAILY, local24HourOfDay, localMinuteOfHour, localTimezone

    Individual:
        enabled, cadence=INDIVIDUAL
    """
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrganizationMetadata:
    r"""Metadata about an organization"""
    UNSET='__SPEAKEASY_UNSET__'
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    creation_time: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('creationTime') }})
    deleted: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deleted') }})
    subscription_tier: Optional[OrganizationMetadataSubscriptionTier] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('subscriptionTier'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    email_domains: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('emailDomains'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    observatory_url: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('observatoryUrl'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    notification_settings: Optional[OrganizationMetadataNotificationSettings] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('notificationSettings'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    use_cloud_front: Optional[bool] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('useCloudFront'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    parent_org_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parentOrgId'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    subscription_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('subscriptionId'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    storage_bucket_override: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('storageBucketOverride'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    allow_managed_membership_updates_only: Optional[bool] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('allowManagedMembershipUpdatesOnly'), 'exclude': lambda f: f is OrganizationMetadata.UNSET }})
    

