"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ProfileTrace:
    r"""A single profile trace item"""
    UNSET='__SPEAKEASY_UNSET__'
    trace_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('traceId') }})
    dataset_timestamp: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('datasetTimestamp'), 'exclude': lambda f: f is ProfileTrace.UNSET }})
    download_url: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('downloadUrl'), 'exclude': lambda f: f is ProfileTrace.UNSET }})
    

