"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .profiletrace import ProfileTrace
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional
from whylabs_client import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ProfileTracesResponse:
    r"""Response for listing profile traces"""
    UNSET='__SPEAKEASY_UNSET__'
    traces: List[ProfileTrace] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('traces') }})
    next_offset: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nextOffset'), 'exclude': lambda f: f is ProfileTracesResponse.UNSET }})
    is_truncated: Optional[bool] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('isTruncated'), 'exclude': lambda f: f is ProfileTracesResponse.UNSET }})
    

