"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Role(str, Enum):
    ADMIN = 'ADMIN'
    MEMBER = 'MEMBER'
    VIEWER = 'VIEWER'
