"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TimePeriod(str, Enum):
    r"""A TimePeriod represents the bucketing that a dataset has undergone."""
    P1_M = 'P1M'
    P1_W = 'P1W'
    P1_D = 'P1D'
    PT1_H = 'PT1H'
